import Footer from "@/components/layout/Footer/Footer";
import Navbar from "@/components/layout/Navbar/Navbar";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const janna = localFont({
  src: [
    {
      path: "../public/fonts/janna/Janna-LT-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/janna/Janna-LT-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-janna",
  display: "swap",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className={janna.variable}>
      <body
        className={``}
      >
        <Navbar />
        <div className="bg-bg">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
